#!/usr/bin/env bash
# A script that transfers a file to your server
# Parameter Key
file_path="$1"
ip="$2"
username="$3"
private_key="$4"

# Check if the parameters are less than 3.
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
elif [ $# -lt 4 ]; then
    # if less than, transfer the file to server disabling strict host key checking
    # finding private key @ default location
    scp -o StrictHostKeyChecking=no "$file_path" "$username@$ip:~/"
else
    # Transfer the file to server disabling strict host key checking
    scp -i "$private_key" -o StrictHostKeyChecking=no "$file_path" "$username@$ip:~/"
fi