#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
# Script displays only: username, user id & Home directory path for the user
while read -r passwd; do
  echo "$passwd" | cut -f 1,3,6 -d ':'
done < "/etc/passwd"
